# -*- coding: utf-8 -*-
"""adventofcode_day_7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Cc_yErAgJjsYDW0BTLrt1HhwKOOq0Lbc
"""

bag_rules = """light red bags contain 1 bright white bag, 2 muted yellow bags.
dark orange bags contain 3 bright white bags, 4 muted yellow bags.
bright white bags contain 1 shiny gold bag.
muted yellow bags contain 2 shiny gold bags, 9 faded blue bags.
shiny gold bags contain 1 dark olive bag, 2 vibrant plum bags.
dark olive bags contain 3 faded blue bags, 4 dotted black bags.
vibrant plum bags contain 5 faded blue bags, 6 dotted black bags.
faded blue bags contain no other bags.
dotted black bags contain no other bags."""

bag_rules = bag_rules.split('\n')

print(bag_rules)

good_bags = set()
potential_bags = set()

def parse_bags(bag_desc,bag_color):

  return bag_type

for rule in bag_rules:
  if 'shiny gold bag' in rule and 'shiny gold bags contain' not in rule:

    good_bags.add(rule.split(' bags')[0])

    print(rule.split('contain ')[1].split())
    bag_iter = 0
    while True:
      try:
        parse_bags(rule.split())
      except IndexError:
        gotdata = 'null'
        return False

    # print(rule.split()[5], rule.split()[6])
    # potential_bags.add
  


print(good_bags)